export default [
  {category: 'Health', 'icon': 'heartbeat'},
  {category: 'Finance', 'icon': 'money-check-alt'},
  {category: 'Career', 'icon': 'briefcase'},
  {category: 'Education', 'icon': 'graduation-cap'},
  {category: 'Social', 'icon': 'comment'},
  {category: 'Personal Growth', 'icon': 'tree'},
  {category: 'Mental', 'icon': 'smile-beam'},
  {category: 'Productivity', 'icon': 'calendar'},
  {category: 'Relationships', 'icon': 'users'},
  {category: 'Spirituality', 'icon': 'praying-hands'},
  {category: 'Sleep', 'icon': 'bed'},
  {category: 'Nutrition', 'icon': 'utensils'},
  {category: 'Fitness', 'icon': 'running'},
  {category: 'Environment', 'icon': 'leaf'},
  {category: 'Other', 'icon': 'ellipsis-h'},
]